[package]
name = "uc-lean"
version = "0.1"
lean_version = "leanprover-community/lean:3.42.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "48eacc63751375da61238b90773c4208e768eabc"}
